build: update assign-reviewer.yml

diff --git a/.github/workflows/assign-reviewer.yml b/.github/workflows/assign-reviewer.yml
--- a/.github/workflows/assign-reviewer.yml
+++ b/.github/workflows/assign-reviewer.yml
@@ -16,30 +16,45 @@ jobs:
       - name: Check out the repository
         uses: actions/checkout@v3
 
-      - name: Set Reviewer
+      - name: Set Reviewer based on Label
         run: |
-          # ラベルと対応するレビュアを定義
           declare -A LABELS_TO_REVIEWERS=(
-            ["feat"]="nekonadocat"
+            ["feat"]="nekonado,nekonadocat"
             ["bug"]="nekonado,nekonadocat"
           )
 
           label="${{ github.event.label.name }}"
           reviewers=${LABELS_TO_REVIEWERS[$label]}
 
+          author_username="${{ github.event.pull_request.user.login }}"
+
           if [ -n "$reviewers" ]; then
-            # GitHub API を呼び出してレビュアを設定
-            curl -s -w "%{http_code}" -o response.txt -X POST \
-              -H "Accept: application/vnd.github.v3+json" \
-              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
-              -H "Content-Type: application/json" \
-              "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
-              -d "{\"reviewers\": [\"$reviewers\"]}"
+            IFS=',' read -ra reviewers_array <<< "$reviewers"
 
-            # API のレスポンスを取得
-            http_code=$(tail -n1 response.txt)
-            body=$(head -n-1 response.txt)
+            filtered_reviewers=()
+            for reviewer in "${reviewers_array[@]}"; do
+              if [ "$reviewer" != "$author_username" ]; then
+                filtered_reviewers+=("$reviewer")
+              fi
+            done
 
-            echo "HTTP Status Code: $http_code"
-            echo "Response Body: $body"
+            if [ ${#filtered_reviewers[@]} -gt 0 ]; then
+              reviewers_json=$(printf '%s\n' "${filtered_reviewers[@]}" | jq -c -R 'split("\n") | map(select(length > 0))')
+
+              response=$(curl -s -o /dev/null -w "%{http_code}\n" -X POST \
+                -H "Accept: application/vnd.github.v3+json" \
+                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
+                -H "Content-Type: application/json" \
+                "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}/requested_reviewers" \
+                -d "{\"reviewers\": $reviewers_json}")
+
+              if [ "$response" -ge 200 ] && [ "$response" -lt 300 ]; then
+                echo "Reviewers set successfully based on label: $label"
+              else
+                echo "Failed to set reviewers. HTTP Status Code: $response"
+                exit 1
+              fi
+            else
+              echo "No valid reviewers found after filtering."
+            fi
           fi
